line_length: 120 # Максимальная длина строки кода, превышение которой вызывает предупреждение.

file_length:
  warning: 500 # Длина файла, при превышении которой будет выдано предупреждение.
  error: 1200 # Длина файла, при превышении которой будет выдана ошибка.

type_name:
  min_length: 3 # Минимальная длина имени типа (например, классов, структур).
  max_length:
    warning: 40 # Максимальная длина имени типа, при превышении которой будет выдано предупреждение.
    error: 50 # Максимальная длина имени типа, при превышении которой будет выдана ошибка.
    
disabled_rules:
  - trailing_comma # Проверка на наличие запятой в конце списков, чтобы избежать ошибок при добавлении новых элементов.

opt_in_rules:
  - attributes # Проверка на правильное использование атрибутов (например, @objc, @available).
  - closure_end_indentation # Проверка отступов в конце замыканий для улучшения читаемости.
  - discouraged_optional_collection # Предупреждение о том, что использование коллекций опционалов (например, [String]? вместо [String]) не рекомендуется.
  - empty_count # Проверка на использование count для проверки на пустоту коллекции (например, вместо `array.count == 0` лучше использовать `array.isEmpty`).
  - empty_string # Предупреждение о пустых строках, которые могут быть неуместными.
  - empty_xctest_method # Проверка на пустые методы тестов XCTest, которые не содержат кода.
  - explicit_init # Требование явного указания инициализатора для классов и структур.
  - fatal_error_message # Проверка на наличие сообщения в вызовах fatalError(), чтобы улучшить отладку.
  - first_where # Рекомендует использовать `first(where:)` вместо `filter` для получения первого элемента, соответствующего условию.
  - lower_acl_than_parent # Предупреждение о том, что уровень доступа (ACL) дочернего элемента ниже, чем у родительского.
  - literal_expression_end_indentation # Проверка отступов в конце литеральных выражений для улучшения читаемости.
  - missing_docs # Проверка на отсутствие документации для публичных методов и классов.
  - modifier_order # Проверка порядка модификаторов доступа (например, public, private) для согласованности.
  - multiline_arguments # Проверка на многострочные аргументы, чтобы улучшить читаемость.
  - multiline_function_chains # Проверка на многострочные цепочки вызовов функций для улучшения читаемости.
  - no_extension_access_modifier # Запрет на использование модификаторов доступа в расширениях, чтобы избежать путаницы.
  - operator_usage_whitespace # Проверка на правильное использование пробелов вокруг операторов для улучшения читаемости.
  - operator_whitespace # Проверка на пробелы вокруг операторов, чтобы поддерживать единообразие.
  - overridden_super_call # Проверка на вызовы super в переопределенных методах, чтобы избежать ошибок.
  - override_in_extension # Предупреждение о переопределении методов в расширениях, что может быть неочевидно.
  - prohibited_super_call # Запрет на вызовы super в определенных контекстах, чтобы избежать ошибок.
  - redundant_nil_coalescing # Проверка на избыточное использование оператора объединения с nil (например, `x ?? nil`).
  - redundant_type_annotation # Проверка на избыточные аннотации типов, которые могут быть выведены компилятором.
  - required_enum_case # Проверка на наличие всех обязательных случаев в перечислениях.
  - single_test_class # Проверка на наличие только одного класса теста в файле, чтобы избежать путаницы.
  - sorted_first_last # Проверка на сортировку методов first и last для согласованности.
  - sorted_imports # Проверка на сортировку импортов для улучшения читаемости.
  - strict_fileprivate # Строгая проверка для использования модификатора fileprivate, чтобы избежать ошибок доступа.
  - trailing_closure # Проверка на использование завершающей скобки для замыканий, чтобы улучшить читаемость.
  - unavailable_function # Проверка на использование недоступных функций, чтобы избежать ошибок выполнения.
  - unneeded_parentheses_in_closure_argument # Проверка на ненужные скобки в аргументах замыканий, чтобы улучшить читаемость.

included:
  - Shift
  
excluded:
  - Pods
