line_length: 120 # Максимальная длина строки кода, превышение которой вызывает предупреждение.

file_length:
  warning: 500 # Длина файла, при превышении которой будет выдано предупреждение.
  error: 1200 # Длина файла, при превышении которой будет выдана ошибка.

type_name:
  min_length: 3 # Минимальная длина имени типа (например, классов, структур).
  max_length:
    warning: 40 # Максимальная длина имени типа, при превышении которой будет выдано предупреждение.
    error: 50 # Максимальная длина имени типа, при превышении которой будет выдана ошибка.
    
disabled_rules:
  - trailing_comma # Правило для проверки на наличие запятой в конце списков, чтобы избежать ошибок при добавлении новых элементов.

opt_in_rules:
  - attributes # Правило для проверки на правильное использование атрибутов (например, @objc, @available).
  - closure_end_indentation # Правило для проверки отступов в конце замыканий для улучшения читаемости.
  - discouraged_optional_collection # Правило для предупреждения о том, что использование коллекций опционалов (например, [String]? вместо [String]) не рекомендуется.
  - empty_count # Правило для проверки на использование count для проверки на пустоту коллекции (например, вместо `array.count == 0` лучше использовать `array.isEmpty`).
  - empty_string # Правило для предупреждения о пустых строках, которые могут быть неуместными.
  - empty_xctest_method # Правило для проверки на пустые методы тестов XCTest, которые не содержат кода.
  - explicit_init # Правило для требования явного указания инициализатора для классов и структур.
  - fatal_error_message # Правило для проверки на наличие сообщения в вызовах fatalError(), чтобы улучшить отладку.
  - first_where # Правило для рекомендации использовать `first(where:)` вместо `filter` для получения первого элемента, соответствующего условию.
  - lower_acl_than_parent # Правило для предупреждения о том, что уровень доступа (ACL) дочернего элемента ниже, чем у родительского.
  - literal_expression_end_indentation # Правило для проверки отступов в конце литеральных выражений для улучшения читаемости.
  - missing_docs # Правило для проверки на отсутствие документации для публичных методов и классов.
  - modifier_order # Правило для проверки порядка модификаторов доступа (например, public, private) для согласованности.
  - multiline_arguments # Правило для проверки на многострочные аргументы, чтобы улучшить читаемость.
  - multiline_function_chains # Правило для проверки на многострочные цепочки вызовов функций для улучшения читаемости.
  - no_extension_access_modifier # Правило для запрета на использование модификаторов доступа в расширениях, чтобы избежать путаницы.
  - operator_usage_whitespace # Правило для проверки на правильное использование пробелов вокруг операторов для улучшения читаемости.
  - operator_whitespace # Правило для проверки на пробелы вокруг операторов, чтобы поддерживать единообразие.
  - overridden_super_call # Правило для проверки на вызовы super в переопределенных методах, чтобы избежать ошибок.
  - override_in_extension # Правило для предупреждения о переопределении методов в расширениях, что может быть неочевидно.
  - prohibited_super_call # Правило для запрета на вызовы super в определенных контекстах, чтобы избежать ошибок.
  - redundant_nil_coalescing # Правило для проверки на избыточное использование оператора объединения с nil (например, `x ?? nil`).
  - redundant_type_annotation # Правило для проверки на избыточные аннотации типов, которые могут быть выведены компилятором.
  - required_enum_case # Правило для проверки на наличие всех обязательных случаев в перечислениях.
  - single_test_class # Правило для проверки на наличие только одного класса теста в файле, чтобы избежать путаницы.
  - sorted_first_last # Правило для проверки на сортировку методов first и last для согласованности.
  - sorted_imports # Правило для проверки на сортировку импортов для улучшения читаемости.
  - strict_fileprivate # Правило для строгой проверки для использования модификатора fileprivate, чтобы избежать ошибок доступа.
  - trailing_closure # Правило для проверки на использование завершающей скобки для замыканий, чтобы улучшить читаемость.
  - unavailable_function # Правило для проверки на использование недоступных функций, чтобы избежать ошибок выполнения.
  - unneeded_parentheses_in_closure_argument # Правило для проверки на ненужные скобки в аргументах замыканий, чтобы улучшить читаемость.
  
# Правило для контроля использования принудительного приведения типов.
force_cast:
  severity: warning

included:
  - Shift
  
excluded:
  - Pods
